/*
 * This file is auto-generated by Android AIDL tool.
 * DO NOT MODIFY manually - any changes will be overwritten.
 *
 * 本文件是 AIDL (Android Interface Definition Language) 工具自动生成的Binder通信接口代码。
 * AIDL 用于实现跨进程通信(IPC)，允许一个进程的客户端调用另一个进程(服务端)的方法。
 *
 * 工作原理：
 * 1. 客户端通过 Stub.asInterface() 获取代理对象(Proxy)
 * 2. 代理对象将方法调用封装为 Parcel 数据，通过 Binder 驱动发送
 * 3. 服务端的 onTransact() 接收数据，反序列化后调用实际方法
 * 4. 结果再通过 Binder 返回给客户端
 */
package kim.hsl.aidl_demo;
// Declare any non-default types here with import statements

/**
 * AIDL 通信接口定义
 *
 * 该接口继承自 IInterface，是跨进程通信的核心接口。
 * 客户端通过 asInterface() 获取实现实例，调用远程方法。
 *
 * 注意：此文件由 AIDL 工具自动生成，不应手动修改。
 */
public interface IMyAidlInterface extends android.os.IInterface {
    /**
     * Default implementation for IMyAidlInterface.
     *
     * 默认实现类 - 当客户端和服务端在同一进程时使用。
     * 此实现不执行任何 IPC 操作，直接在本地调用方法。
     */
    public static class Default implements kim.hsl.aidl_demo.IMyAidlInterface {
        /**
         * Demonstrates some basic types that you can use as parameters
         * and return values in AIDL.
         *
         * 示例方法：演示 AIDL 支持的基本数据类型参数和返回值。
         *
         * @param anInt   整型参数
         * @param aLong   长整型参数
         * @param aBoolean 布尔型参数
         * @param aFloat  浮点型参数
         * @param aDouble 双精度浮点型参数
         * @param aString 字符串参数
         */
        @Override
        public void basicTypes(int anInt, long aLong, boolean aBoolean, float aFloat, double aDouble, java.lang.String aString) throws android.os.RemoteException {
        }

        /**
         * 添加学生到列表
         *
         * 参数方向说明：
         * - in:  数据从客户端写入服务端（客户端传入，服务端接收）
         * - out: 数据从服务端输出到客户端（服务端写入，客户端接收）
         * - inout: 双向数据传递（既写入又输出）
         *
         * 此方法使用 in 方向：Student 对象从客户端传递到服务端
         *
         * @param student 要添加的学生对象（实现了 Parcelable 接口）
         */
        @Override
        public void addStudent(kim.hsl.aidl_demo.Student student) throws android.os.RemoteException {
        }

        /**
         * 获取 Student 集合
         *
         * 获取服务端存储的学生列表
         *
         * @return 学生对象列表（List<Student>）
         */
        @Override
        public java.util.List<kim.hsl.aidl_demo.Student> getStudents() throws android.os.RemoteException {
            return null;
        }

        @Override
        public android.os.IBinder asBinder() {
            return null;
        }
    }

    /**
     * Stub - 本地端 IPC 实现基类
     *
     * Stub 是 Binder 服务端的核心类，继承自 android.os.Binder。
     * 它的工作：
     * 1. 接收客户端通过 transact() 发送的请求
     * 2. 在 onTransact() 中解析请求，执行实际方法
     * 3. 将结果写入 reply Parcel 返回给客户端
     *
     * 继承关系：Stub extends Binder implements IMyAidlInterface
     */
    public static abstract class Stub extends android.os.Binder implements kim.hsl.aidl_demo.IMyAidlInterface {
        /**
         * DESCRIPTOR - 接口标识符
         *
         * 用于在 Binder 驱动中标识这个接口。
         * 当多个服务运行时，DESCRIPTOR 帮助区分不同的 AIDL 接口。
         */
        private static final java.lang.String DESCRIPTOR = "kim.hsl.aidl_demo.IMyAidlInterface";

        /**
         * 构造方法 - 创建 Stub 并绑定接口描述符
         *
         * attachInterface() 将此 Stub 与 DESCRIPTOR 关联，
         * 使得后续 queryLocalInterface() 能够通过 DESCRIPTOR 找到这个接口。
         */
        public Stub() {
            this.attachInterface(this, DESCRIPTOR);
        }

        /**
         * 将 IBinder 转换为 AIDL 接口
         *
         * 这是客户端获取远程服务的主要入口点。
         *
         * 工作流程：
         * 1. 如果 obj 为 null，返回 null
         * 2. 查询本地是否有对应接口（同一进程内直接返回）
         * 3. 跨进程时，创建 Proxy 代理对象，客户端通过代理调用远程方法
         *
         * @param obj IBinder 对象（由 ServiceConnection.onServiceConnected() 提供）
         * @return AIDL 接口实现（本地 Stub 或远程 Proxy）
         */
        public static kim.hsl.aidl_demo.IMyAidlInterface asInterface(android.os.IBinder obj) {
            if ((obj == null)) {
                return null;
            }
            android.os.IInterface iin = obj.queryLocalInterface(DESCRIPTOR);
            if (((iin != null) && (iin instanceof kim.hsl.aidl_demo.IMyAidlInterface))) {
                return ((kim.hsl.aidl_demo.IMyAidlInterface) iin);
            }
            return new kim.hsl.aidl_demo.IMyAidlInterface.Stub.Proxy(obj);
        }

        @Override
        public android.os.IBinder asBinder() {
            return this;
        }

        /**
         * onTransact - Binder 事务处理核心方法
         *
         * 此方法运行在 Binder 线程池中，由 Binder 驱动调用。
         * 它根据 code 区分不同的 AIDL 方法，并处理参数序列化/反序列化。
         *
         * @param code   事务码，标识要调用的方法（TRANSACTION_xxx）
         * @param data   输入数据，包含序列化后的参数
         * @param reply  输出数据，包含序列化后的返回值
         * @param flags  额外标志位（如 FLAG_ONEWAY 表示无返回值）
         * @return true 表示成功处理，false 表示失败
         */
        @Override
        public boolean onTransact(int code, android.os.Parcel data, android.os.Parcel reply, int flags) throws android.os.RemoteException {
            java.lang.String descriptor = DESCRIPTOR;
            switch (code) {
                // INTERFACE_TRANSACTION - 获取接口描述符
                // Binder 驱动在 linkToDeath 等操作时会调用此码
                case INTERFACE_TRANSACTION: {
                    reply.writeString(descriptor);
                    return true;
                }
                // TRANSACTION_basicTypes - basicTypes 方法
                // 处理 6 个基本类型参数的序列化和反序列化
                case TRANSACTION_basicTypes: {
                    data.enforceInterface(descriptor);
                    int _arg0;
                    _arg0 = data.readInt();
                    long _arg1;
                    _arg1 = data.readLong();
                    boolean _arg2;
                    _arg2 = (0 != data.readInt());
                    float _arg3;
                    _arg3 = data.readFloat();
                    double _arg4;
                    _arg4 = data.readDouble();
                    java.lang.String _arg5;
                    _arg5 = data.readString();
                    // 调用实际的服务端实现
                    this.basicTypes(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
                    reply.writeNoException();
                    return true;
                }
                // TRANSACTION_addStudent - addStudent 方法
                // 处理 Student 对象的 in 方向传递
                case TRANSACTION_addStudent: {
                    data.enforceInterface(descriptor);
                    // 从 data 中反序列化 Student 对象
                    // Parcelable 序列化格式：writeInt() 判断非空 + writeToParcel() 写入数据
                    kim.hsl.aidl_demo.Student _arg0;
                    if ((0 != data.readInt())) {
                        _arg0 = kim.hsl.aidl_demo.Student.CREATOR.createFromParcel(data);
                    } else {
                        _arg0 = null;
                    }
                    // 调用实际的服务端实现
                    this.addStudent(_arg0);
                    reply.writeNoException();
                    // 如果参数使用 out/inout 方向，这里会将修改后的对象写回 reply
                    if ((_arg0 != null)) {
                        reply.writeInt(1);
                        _arg0.writeToParcel(reply, android.os.Parcelable.PARCELABLE_WRITE_RETURN_VALUE);
                    } else {
                        reply.writeInt(0);
                    }
                    return true;
                }
                // TRANSACTION_getStudents - getStudents 方法
                // 返回 List<Student> 集合
                case TRANSACTION_getStudents: {
                    data.enforceInterface(descriptor);
                    java.util.List<kim.hsl.aidl_demo.Student> _result = this.getStudents();
                    reply.writeNoException();
                    // writeTypedList() 批量写入 List 中的所有元素
                    reply.writeTypedList(_result);
                    return true;
                }
                // 默认处理：未知事务码，交给父类处理
                default: {
                    return super.onTransact(code, data, reply, flags);
                }
            }
        }

        /**
         * Proxy - 远程代理类（运行在客户端进程）
         *
         * Proxy 是 Stub 的内部类，实现了 IMyAidlInterface 接口。
         * 它在客户端进程中运行，封装了远程调用的细节。
         *
         * 工作流程：
         * 1. 客户端调用 Proxy 方法（如 addStudent）
         * 2. Proxy 将参数序列化到 Parcel _data 中
         * 3. 通过 mRemote.transact() 发送到 Binder 驱动
         * 4. 等待服务端返回结果，从 Parcel _reply 中反序列化
         * 5. 返回给调用者
         */
        private static class Proxy implements kim.hsl.aidl_demo.IMyAidlInterface {
            /** mRemote - 指向远程 Binder 的引用 */
            private android.os.IBinder mRemote;

            /**
             * 构造方法 - 持有远程 IBinder 引用
             *
             * @param remote 服务端的 Binder 引用
             */
            Proxy(android.os.IBinder remote) {
                mRemote = remote;
            }

            @Override
            public android.os.IBinder asBinder() {
                return mRemote;
            }

            /**
             * 获取接口描述符
             *
             * @return 接口标识符字符串
             */
            public java.lang.String getInterfaceDescriptor() {
                return DESCRIPTOR;
            }

            /**
             * 示例方法：演示 AIDL 基本类型参数传递
             *
             * 客户端调用此方法时，Proxy 会：
             * 1. 获取两个 Parcel 对象（_data 用于输入，_reply 用于输出）
             * 2. 将 6 个基本类型参数依次写入 _data
             * 3. 调用 transact() 发送请求到远程服务端
             * 4. 从 _reply 中读取异常信息（如果有）
             * 5. 回收 Parcel 对象
             *
             * @param anInt    整型
             * @param aLong    长整型
             * @param aBoolean 布尔型（转换为 int: 0=false, 1=true）
             * @param aFloat   浮点型
             * @param aDouble  双精度浮点型
             * @param aString  字符串
             */
            @Override
            public void basicTypes(int anInt, long aLong, boolean aBoolean, float aFloat, double aDouble, java.lang.String aString) throws android.os.RemoteException {
                android.os.Parcel _data = android.os.Parcel.obtain();
                android.os.Parcel _reply = android.os.Parcel.obtain();
                try {
                    _data.writeInterfaceToken(DESCRIPTOR);
                    _data.writeInt(anInt);
                    _data.writeLong(aLong);
                    _data.writeInt(((aBoolean) ? (1) : (0)));
                    _data.writeFloat(aFloat);
                    _data.writeDouble(aDouble);
                    _data.writeString(aString);
                    // 发送 transact 请求到远程 Binder
                    boolean _status = mRemote.transact(Stub.TRANSACTION_basicTypes, _data, _reply, 0);
                    if (!_status && getDefaultImpl() != null) {
                        getDefaultImpl().basicTypes(anInt, aLong, aBoolean, aFloat, aDouble, aString);
                        return;
                    }
                    // 读取服务端返回的异常信息
                    _reply.readException();
                } finally {
                    _reply.recycle();
                    _data.recycle();
                }
            }

            /**
             * 添加学生到远程服务
             *
             * 参数方向 in：数据从客户端流向服务端
             *
             * Parcelable 对象序列化格式：
             * - writeInt(1) + writeToParcel() 表示非空对象
             * - writeInt(0) 表示空对象
             *
             * @param student 要添加的学生对象
             */
            @Override
            public void addStudent(kim.hsl.aidl_demo.Student student) throws android.os.RemoteException {
                android.os.Parcel _data = android.os.Parcel.obtain();
                android.os.Parcel _reply = android.os.Parcel.obtain();
                try {
                    _data.writeInterfaceToken(DESCRIPTOR);
                    if ((student != null)) {
                        _data.writeInt(1);
                        student.writeToParcel(_data, 0);
                    } else {
                        _data.writeInt(0);
                    }
                    // 发送 transact 请求
                    boolean _status = mRemote.transact(Stub.TRANSACTION_addStudent, _data, _reply, 0);
                    if (!_status && getDefaultImpl() != null) {
                        getDefaultImpl().addStudent(student);
                        return;
                    }
                    _reply.readException();
                    // 处理 out 参数返回值（如果服务端修改了 student 对象）
                    if ((0 != _reply.readInt())) {
                        student.readFromParcel(_reply);
                    }
                } finally {
                    _reply.recycle();
                    _data.recycle();
                }
            }

            /**
             * 获取远程服务的学生列表
             *
             * 返回值是 List<Student> 类型，通过 createTypedArrayList() 反序列化。
             *
             * @return 学生列表
             */
            @Override
            public java.util.List<kim.hsl.aidl_demo.Student> getStudents() throws android.os.RemoteException {
                android.os.Parcel _data = android.os.Parcel.obtain();
                android.os.Parcel _reply = android.os.Parcel.obtain();
                java.util.List<kim.hsl.aidl_demo.Student> _result;
                try {
                    _data.writeInterfaceToken(DESCRIPTOR);
                    boolean _status = mRemote.transact(Stub.TRANSACTION_getStudents, _data, _reply, 0);
                    if (!_status && getDefaultImpl() != null) {
                        return getDefaultImpl().getStudents();
                    }
                    _reply.readException();
                    // 从 reply 中反序列化 List<Student>
                    _result = _reply.createTypedArrayList(kim.hsl.aidl_demo.Student.CREATOR);
                } finally {
                    _reply.recycle();
                    _data.recycle();
                }
                return _result;
            }

            /**
             * sDefaultImpl - 默认实现实例
             *
             * 用于同一进程内的默认实现（Fallback机制）。
             * 当 transact() 返回 false 时，尝试调用默认实现。
             */
            public static kim.hsl.aidl_demo.IMyAidlInterface sDefaultImpl;
        }

        /**
         * 事务码定义
         *
         * 每个 AIDL 方法对应一个事务码，
         * FIRST_CALL_TRANSACTION 是 AIDL 事务码的起始值。
         */
        static final int TRANSACTION_basicTypes = (android.os.IBinder.FIRST_CALL_TRANSACTION + 0);
        static final int TRANSACTION_addStudent = (android.os.IBinder.FIRST_CALL_TRANSACTION + 1);
        static final int TRANSACTION_getStudents = (android.os.IBinder.FIRST_CALL_TRANSACTION + 2);

        /**
         * 设置默认实现（用于同一进程内的 Fallback）
         *
         * 当跨进程调用失败时，会尝试使用默认实现。
         * 此方法只能调用一次，多次调用会抛出异常。
         *
         * @param impl 默认实现实例
         * @return 设置是否成功
         */
        public static boolean setDefaultImpl(kim.hsl.aidl_demo.IMyAidlInterface impl) {
            if (Stub.Proxy.sDefaultImpl != null) {
                throw new IllegalStateException("setDefaultImpl() called twice");
            }
            if (impl != null) {
                Stub.Proxy.sDefaultImpl = impl;
                return true;
            }
            return false;
        }

        /**
         * 获取默认实现实例
         *
         * @return 默认实现，如果未设置则返回 null
         */
        public static kim.hsl.aidl_demo.IMyAidlInterface getDefaultImpl() {
            return Stub.Proxy.sDefaultImpl;
        }
    }

    /**
     * 示例方法：演示 AIDL 基本数据类型
     *
     * AIDL 支持的基本类型：int, long, boolean, float, double, String
     * 以及它们的数组形式：int[], String[] 等
     *
     * @param anInt    整型
     * @param aLong    长整型
     * @param aBoolean 布尔型
     * @param aFloat   浮点型
     * @param aDouble  双精度浮点型
     * @param aString  字符串
     */
    public void basicTypes(int anInt, long aLong, boolean aBoolean, float aFloat, double aDouble, java.lang.String aString) throws android.os.RemoteException;

    /**
     * 添加学生到远程服务
     *
     * 参数方向说明：
     * - in:      数据从客户端写入服务端（客户端传入，服务端接收）
     * - out:     数据从服务端输出到客户端（服务端写入，客户端接收）
     * - inout:   双向数据传递（既写入又输出）
     *
     * @param student 要添加的学生对象（必须实现 Parcelable 接口）
     */
    public void addStudent(kim.hsl.aidl_demo.Student student) throws android.os.RemoteException;

    /**
     * 获取学生列表
     *
     * 从远程服务获取学生对象列表。
     *
     * @return 学生对象列表
     */
    public java.util.List<kim.hsl.aidl_demo.Student> getStudents() throws android.os.RemoteException;
}